name: New Application Request
description: Use this form to command the AI to generate a new project.
title: "[App Request]: "
labels: ["ai-request"]
body:
  - type: input
    id: repo_name
    attributes:
      label: New Repository Name
      description: The name for the new project folder and GitHub repo (e.g., my-cool-app).
      placeholder: my-flutter-notes-app
    validations:
      required: true

  - type: dropdown
    id: language
    attributes:
      label: Language or Framework
      options:
        - Flutter
        - Python
        # Bạn có thể thêm các lựa chọn khác ở đây trong tương lai
        # - React
        # - FastAPI
      default: 0
    validations:
      required: true

  - type: dropdown
    id: ai_model
    attributes:
      label: Gemini Model
      description: Choose the AI brain to generate the code.
      options:
        - gemini-1.5-flash-latest
        - gemini-1.5-pro-latest
      default: 0
    validations:
      required: true

  - type: textarea
    id: prompt
    attributes:
      label: Detailed Prompt (The Blueprint)
      description: Describe in detail the application you want the AI to create.
      placeholder: "Create a simple note-taking app with add and delete functionality..."
      render: "text"
    validations:
      required: true
