name: AI Project Builder from Issue

on:
  issues:
    types: [opened]

jobs:
  generate-app:
    if: "!contains(github.event.issue.labels.*.name, 'bug-report')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Factory Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies for PyNaCl
        run: sudo apt-get update && sudo apt-get install -y libsodium-dev

      - name: Install Python Dependencies
        run: pip install google-generativeai requests pynacl

      - name: Run AI Genesis Script
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GH_USER: ${{ secrets.GH_USER }}
          COMMIT_EMAIL: ${{ secrets.COMMIT_EMAIL }}
          COMMIT_NAME: ${{ secrets.COMMIT_NAME }}
          # Cung cấp các secret của Keystore cho script
          RELEASE_KEYSTORE_BASE64: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: python .github/scripts/genesis.py
