name: AI Project Builder from Issue

on:
  issues:
    types: [opened]

jobs:
  generate-app:
    if: "!contains(github.event.issue.labels.*.name, 'bug-report')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Factory Code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Python Dependencies
        run: pip install google-generativeai requests
      - name: Run AI Genesis Script
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GH_USER: ${{ secrets.GH_USER }}
          COMMIT_EMAIL: ${{ secrets.COMMIT_EMAIL }}
          COMMIT_NAME: ${{ secrets.COMMIT_NAME }}
        run: python .github/scripts/genesis.py
