name: AI App Generator from Issue

# Kích hoạt workflow này mỗi khi một issue mới được mở
on:
  issues:
    types: [opened]

jobs:
  generate-app-from-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (của repo điều khiển)
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install google-generativeai PyGithub

      - name: Run Generation Script
        # Bước này sẽ chạy script Python để thực hiện toàn bộ logic
        # Chúng ta truyền các secret và thông tin issue qua biến môi trường
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: python .github/scripts/generate_app.py
