name: AI Project Builder (Main)

on:
  workflow_dispatch:
    inputs:
      repo_name: { required: true }
      language: { required: true }
      ai_model: { required: true }
      prompt: { required: true }
      issue_number: { required: true }

jobs:
  generate-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - run: pip install google-generativeai requests

      - name: 'Tạo "Issue Body" giả lập'
        id: build_body
        run: |
          issue_body=$(cat <<EOF
          ### New Repository Name
          ${{ github.event.inputs.repo_name }}
          ### Language or Framework
          ${{ github.event.inputs.language }}
          ### Gemini Model
          ${{ github.event.inputs.ai_model }}
          ### Detailed Prompt (The Blueprint)
          ${{ github.event.inputs.prompt }}
          EOF
          )
          echo "issue_body<<EOF" >> $GITHUB_OUTPUT
          echo "$issue_body" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run AI Genesis Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          ISSUE_BODY: ${{ steps.build_body.outputs.issue_body }}
          ISSUE_NUMBER: ${{ github.event.inputs.issue_number }}
          GH_USER: ${{ secrets.GH_USER }}
          COMMIT_EMAIL: ${{ secrets.COMMIT_EMAIL }}
          COMMIT_NAME: ${{ secrets.COMMIT_NAME }}
        run: python .github/scripts/genesis.py
